language: node_js

cache:
  directories:
    - ~/.npm
notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '7'
  - '6'

branches:
  only:
    - "master"

before_install:
- npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - npm run verify

after_script: greenkeeper-lockfile-upload

after_success:
  - npm install coveralls && npm run coveralls
