version: 2
workflows:
  version: 2
  all:
    jobs:
      - node-latest
      - node11:
          requires:
            - node-latest
      - node10:
          requires:
            - node-latest
      - node8:
          requires:
            - node-latest
jobs:
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          key: node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn
            fi
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: npm run verify
      - run: npx codecov
      - store_test_results:
          path: .reports/junit
      - persist_to_workspace:
          root: '.'
          paths:
            - dist
            - lib
            - libm
            - node_modules
  node11:
    docker:
      - image: 'circleci/node:11'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn test --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node10:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn test --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn test --maxWorkers=2
      - store_test_results:
          path: .reports/junit
