ignores:
  - '@babel/core'
  - '@commitlint/*'
  - '@repobuddy/*'
  - '@rollup/plugin-typescript'
  - '@size-limit/preset-small-lib'
  - '@types/jest'
  - eslint-*
  - jest*
  - rimraf # depcheck false negative
  - rollup*
  - ts-jest
  - tslib
