name: pull-request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: stable-packages/.github/.github/workflows/pnpm-verify-cross-platform.yml@main
    with:
      node-version: '[16, 18]'
