name: pull-request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: stable-packages/.github/.github/workflows/pnpm-verify.yml@main
    with:
      artifact_paths: |
        packages/global-store/coverage
        packages/global-store/dist
        packages/global-store/lib
        packages/stable-store/coverage
        packages/stable-store/esm
  coverage:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.6
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: codecov - global-store
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/global-store/coverage/coverage-final.json
          flags: global-store
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: codecov - stable-store
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/stable-store/coverage/coverage-final.json
          flags: stable-store
          token: ${{ secrets.CODECOV_TOKEN }}